name: Code Quality Checks
on: [push]

jobs:
  format-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort
      
      - name: Check imports with isort
        run: |
          isort --check --diff $(git ls-files '*.py')
      
      - name: Check code formatting with Black
        run: |
          black --check --diff $(git ls-files '*.py')